require 'simple_form'
require "simple_form_bootstrap_inputs/railtie"
require "simple_form_bootstrap_inputs/currency_input"
require "simple_form_bootstrap_inputs/date_picker_input"
require "simple_form_bootstrap_inputs/datetime_picker_input"

module SimpleFormBootstrapInputs
end
